### ISSUE TITLE
a bit of instruction & clarification, please…

### ISSUE THREAD

**Issue by lwb52** [JeppeKlitgaard/barista#1]
how to install barista?? using brew, or ??
does the programmatic implementation of pre/post-"s" mean that key does not need to be pressed, and if so: what triggers the action?

**Comment by JeppeKlitgaard** [comment]
I don't really offer support on Barista for now and getting it set up will likely require some knowledge of the Python eco-system on the user's end.

As stated in the README, it is very much a personal project for now, but may turn into Espanso packages in the future. Barista is essentially a 'compiler' for a different, more flexible configuration layout. It uses `jsonnet` to compile the configuration into the Espanso format.

If you do want to venture further, I would have a look at the Python ecosystem and `poetry` in particular.

Programmatic implementation means that the pre and post triggers can be specified in a single place prior to compilation. Equally triggers and replacements can be defined programmatically using `jsonnet`.

**Comment by lwb52** [comment]
Thanks ever so much for your informative & helpful response!!
-L.W. Brown
